import type { ModelMessage } from "../models/types.js";
import type { Step } from "../types/events.js";

/**
 * Message assembler for cache-friendly prefix construction (B1/B2).
 *
 * Produces a stable, byte-identical prefix from:
 *   [tools schema] + [system prompt] + [few-shot examples]  ← immutable, cache-breakpointed (B1)
 *   [stable history chunks]                                  ← filled segments, cache-breakpointed (B2)
 *   [incremental tail]                                       ← current step, not cached
 *
 * B2 segment caching: once the history reaches a multiple of chunkSizeSteps,
 * the last message in that completed chunk gets a cache breakpoint. The prefix
 * up to that point is byte-identical across future steps and qualifies for
 * Anthropic's long-TTL (5 min) prompt cache.
 *
 * Replaces smolagents' write_memory_to_messages (agents.py:758) which rebuilds
 * the full message list every step (O(steps) token growth, zero caching).
 */
export interface AssemblerConfig {
  systemPrompt: string;
  toolsSchema: object[];
  fewShotExamples?: ModelMessage[];
  /**
   * Chunk size in steps before sealing a history segment with a cache breakpoint (B2).
   * Default: 0 (disabled — only the system prefix is cached).
   * Recommended: 5–10 for long-running agents.
   */
  chunkSizeSteps?: number;
}

export class MessageAssembler {
  #config: AssemblerConfig;
  #history: Step[] = [];
  /** Cached ModelMessage[] per step, built once in addStep() instead of every build(). */
  #msgCache: ModelMessage[][] = [];
  /** Cached system message — built once at construction time (system prompt and tools never change). */
  readonly #systemMsg: ModelMessage;
  /** Set of history indices that are the last step of a sealed B2 chunk. Maintained incrementally in addStep(). */
  #sealedAt: Set<number> = new Set();
  /** Running total of messages across all cached steps — used to pre-allocate build() result. */
  #flatMsgCount = 0;

  constructor(config: AssemblerConfig) {
    this.#config = config;
    this.#systemMsg = {
      role: "system",
      content: this.#buildSystemContent(),
      cacheBreakpoint: { afterBlockIndex: 0, type: "ephemeral" },
    };
  }

  addStep(step: Step): void {
    this.#history.push(step);
    const msgs = this.#stepToMessages(step);
    this.#msgCache.push(msgs);
    this.#flatMsgCount += msgs.length;

    // Incrementally maintain sealed chunk boundaries (B2) so build() never recomputes.
    const chunkSize = this.#config.chunkSizeSteps ?? 0;
    if (chunkSize > 0 && this.#isChunkableStep(step)) {
      const actionCount = this.#history.filter((s) => this.#isChunkableStep(s)).length;
      if (actionCount % chunkSize === 0) {
        this.#sealedAt.add(this.#history.length - 1);
      }
    }
  }

  /**
   * Build the full message list for the next model call.
   *
   * Pre-allocates the result array to the exact required size and fills by index,
   * avoiding push() resizing and spread intermediate allocations.
   * Sealed chunk boundaries are maintained incrementally in addStep(), so build()
   * needs no extra traversal beyond the single assembly loop.
   */
  build(): ModelMessage[] {
    const fewShot = this.#config.fewShotExamples?.length ?? 0;
    const total = 1 + fewShot + this.#flatMsgCount;
    const messages: ModelMessage[] = new Array(total);
    let idx = 0;

    // 1. System prompt — cached at construction time (B1).
    messages[idx++] = this.#systemMsg;

    // 2. Few-shot examples — immutable.
    if (fewShot) {
      for (const m of this.#config.fewShotExamples!) messages[idx++] = m;
    }

    // 3. Assemble history from cache using index-assignment (no push, no spread).
    for (let i = 0; i < this.#msgCache.length; i++) {
      const stepMsgs = this.#msgCache[i]!;
      if (stepMsgs.length === 0) continue;

      if (this.#sealedAt.has(i)) {
        // Seal last message with a cache breakpoint (B2); copy others by reference.
        for (let j = 0; j < stepMsgs.length - 1; j++) messages[idx++] = stepMsgs[j]!;
        messages[idx++] = {
          ...stepMsgs.at(-1)!,
          cacheBreakpoint: { afterBlockIndex: 0, type: "ephemeral" },
        };
      } else {
        for (const m of stepMsgs) messages[idx++] = m;
      }
    }

    return messages;
  }

  reset(): void {
    this.#history = [];
    this.#msgCache = [];
    this.#sealedAt = new Set();
    this.#flatMsgCount = 0;
  }

  /** Current history length (number of steps recorded). */
  get historyLength(): number { return this.#history.length; }

  /**
   * Compact long history by summarizing older steps (P4).
   *
   * Keeps the most recent `keepRecentSteps` steps verbatim and replaces all
   * older steps with a single summary step (a planning step whose `plan` field
   * holds the compressed text). The summary is generated by calling `model`.
   *
   * This reduces context window consumption without discarding agent state.
   * Only call when history is genuinely long; use `estimateMessagesTokens` to
   * check token count first.
   *
   * @param model           Model used to generate the summary.
   * @param keepRecentSteps Number of recent steps to preserve verbatim (default 5).
   * @returns               Number of steps that were compacted into the summary.
   */
  async compact(
    model: import("../models/types.js").Model,
    keepRecentSteps = 5
  ): Promise<number> {
    if (this.#history.length <= keepRecentSteps) return 0;

    const cutoff = this.#history.length - keepRecentSteps;
    const toSummarize = this.#history.slice(0, cutoff);
    const recent = this.#history.slice(cutoff);

    // Build a minimal message list representing only the steps to summarize.
    const summaryContext: import("../models/types.js").ModelMessage[] = [
      {
        role: "system",
        content:
          "You are a concise summarizer. Compress the following agent history into a short, factual summary that preserves key observations, decisions, and results needed to continue the task. Respond with only the summary text.",
      },
    ];
    for (const step of toSummarize) {
      const msgs = this.#stepToMessages(step);
      summaryContext.push(...msgs);
    }
    summaryContext.push({
      role: "user",
      content: "Summarize the history above into a concise paragraph.",
    });

    let summaryText = "";
    for await (const ev of model.generate(summaryContext, { stream: true, maxTokens: 512 })) {
      if (ev.type === "text_delta" && ev.delta) summaryText += ev.delta;
    }
    summaryText = summaryText.trim() || "(no summary generated)";

    // Replace old steps with a single planning/summary step.
    const summaryStep: import("../types/events.js").PlanningStep = {
      type: "planning",
      plan: summaryText,
      facts: `Compacted ${cutoff} steps.`,
    };

    this.#history = [summaryStep, ...recent];
    this.#msgCache = [
      this.#stepToMessages(summaryStep),
      ...recent.map((s) => this.#stepToMessages(s)),
    ];
    // Rebuild derived state from the compacted history.
    this.#flatMsgCount = this.#msgCache.reduce((sum, msgs) => sum + msgs.length, 0);
    this.#sealedAt = new Set();
    const chunkSize = this.#config.chunkSizeSteps ?? 0;
    if (chunkSize > 0) {
      let actionCount = 0;
      for (let i = 0; i < this.#history.length; i++) {
        if (this.#isChunkableStep(this.#history[i]!)) {
          actionCount++;
          if (actionCount % chunkSize === 0) this.#sealedAt.add(i);
        }
      }
    }
    return cutoff;
  }

  /** Returns the number of completed sealed chunks in the current history (B2). */
  get sealedChunkCount(): number {
    return this.#sealedAt.size;
  }

  /** True for step types that count toward B2 chunk boundaries. */
  #isChunkableStep(step: Step): boolean {
    return step.type === "action" || step.type === "tool_use" || step.type === "parallel_tool_use";
  }

  /** Stable representation of system content + tools schema (B1 byte-stability). */
  #buildSystemContent(): string {
    const toolsJson = JSON.stringify(this.#config.toolsSchema, null, 0);
    return `${this.#config.systemPrompt}\n\n<tools>${toolsJson}</tools>`;
  }

  #stepToMessages(step: Step): ModelMessage[] {
    switch (step.type) {
      case "action":
        return [
          {
            role: "assistant",
            content: `<thoughts>${step.thoughts}</thoughts>\n<code>${step.code}</code>`,
          },
          {
            role: "user",
            content: `<observation>${step.observations}</observation>`,
          },
        ];
      case "tool_use":
        // Produce the assistant tool_use block + user tool_result block required
        // by the Anthropic and OpenAI multi-turn tool conversation format.
        return [
          {
            role: "assistant",
            content: [
              ...(step.thoughts
                ? [{ type: "text" as const, text: step.thoughts }]
                : []),
              {
                type: "tool_use" as const,
                id: step.toolCallId,
                name: step.toolName,
                input: step.toolInput,
              },
            ],
          },
          {
            role: "user",
            content: [
              {
                type: "tool_result" as const,
                toolUseId: step.toolCallId,
                content: step.toolOutput || "Tool execution failed with no output.",
                ...(step.isError ? { isError: true as const } : {}),
              },
            ],
          },
        ];
      case "parallel_tool_use":
        // One assistant message with N tool_use blocks + one user message with N
        // tool_result blocks in matching order — required by the Anthropic API
        // when the model calls multiple tools in a single turn.
        return [
          {
            role: "assistant",
            content: [
              ...(step.thoughts
                ? [{ type: "text" as const, text: step.thoughts }]
                : []),
              ...step.calls.map((c) => ({
                type: "tool_use" as const,
                id: c.toolCallId,
                name: c.toolName,
                input: c.toolInput,
              })),
            ],
          },
          {
            role: "user",
            content: step.calls.map((c) => ({
              type: "tool_result" as const,
              toolUseId: c.toolCallId,
              content: c.toolOutput || "Tool execution failed with no output.",
              ...(c.isError ? { isError: true as const } : {}),
            })),
          },
        ];
      case "planning":
        return [
          {
            role: "assistant",
            content: `<plan>${step.plan}</plan>\n<facts>${step.facts}</facts>`,
          },
        ];
      case "final_answer":
        return [];
      case "user_message":
        return [{ role: "user", content: step.content }];
    }
  }
}
