import type { ModelMessage } from "../models/types.js";
import type { Step } from "../types/events.js";

/**
 * Message assembler for cache-friendly prefix construction (B1/B2).
 *
 * Produces a stable, byte-identical prefix from:
 *   [tools schema] + [system prompt] + [few-shot examples]  ← immutable, cache-breakpointed (B1)
 *   [stable history chunks]                                  ← filled segments, cache-breakpointed (B2)
 *   [incremental tail]                                       ← current step, not cached
 *
 * B2 segment caching: once the history reaches a multiple of chunkSizeSteps,
 * the last message in that completed chunk gets a cache breakpoint. The prefix
 * up to that point is byte-identical across future steps and qualifies for
 * Anthropic's long-TTL (5 min) prompt cache.
 *
 * Replaces smolagents' write_memory_to_messages (agents.py:758) which rebuilds
 * the full message list every step (O(steps) token growth, zero caching).
 */
export interface AssemblerConfig {
  systemPrompt: string;
  toolsSchema: object[];
  fewShotExamples?: ModelMessage[];
  /**
   * Chunk size in steps before sealing a history segment with a cache breakpoint (B2).
   * Default: 0 (disabled — only the system prefix is cached).
   * Recommended: 5–10 for long-running agents.
   */
  chunkSizeSteps?: number;
}

export class MessageAssembler {
  #config: AssemblerConfig;
  #history: Step[] = [];
  /** Cached ModelMessage[] per step, built once in addStep() instead of every build(). */
  #msgCache: ModelMessage[][] = [];

  constructor(config: AssemblerConfig) {
    this.#config = config;
  }

  addStep(step: Step): void {
    this.#history.push(step);
    this.#msgCache.push(this.#stepToMessages(step));
  }

  /**
   * Build the full message list for the next model call.
   *
   * The immutable prefix (tools + system + few-shot) is always placed first
   * and ends with a cache breakpoint so Anthropic's prefix cache can save it.
   * Completed history chunks are also breakpointed (B2).
   *
   * O(n) per call: each step's messages are cached in #msgCache at addStep() time,
   * so build() only iterates once to assemble the final array.
   */
  build(): ModelMessage[] {
    const messages: ModelMessage[] = [];

    // 1. System prompt — immutable, always first (B1).
    messages.push({
      role: "system",
      content: this.#buildSystemContent(),
      cacheBreakpoint: { afterBlockIndex: 0, type: "ephemeral" },
    });

    // 2. Few-shot examples — immutable.
    if (this.#config.fewShotExamples?.length) {
      messages.push(...this.#config.fewShotExamples);
    }

    // 3. Determine B2 chunk seal positions (one pass over #history).
    const chunkSize = this.#config.chunkSizeSteps ?? 0;
    const sealedChunkEnds = this.#computeSealedChunkEnds(chunkSize);

    // 4. Assemble from cache — O(n) total.
    for (let i = 0; i < this.#msgCache.length; i++) {
      const stepMsgs = this.#msgCache[i]!;
      if (stepMsgs.length === 0) continue;

      if (sealedChunkEnds.has(i)) {
        // Add breakpoint to the last message of this sealed chunk (B2).
        // Slice avoids mutating the cached array.
        messages.push(...stepMsgs.slice(0, -1));
        messages.push({
          ...stepMsgs.at(-1)!,
          cacheBreakpoint: { afterBlockIndex: 0, type: "ephemeral" },
        });
      } else {
        messages.push(...stepMsgs);
      }
    }

    return messages;
  }

  reset(): void {
    this.#history = [];
    this.#msgCache = [];
  }

  /** Current history length (number of steps recorded). */
  get historyLength(): number { return this.#history.length; }

  /**
   * Compact long history by summarizing older steps (P4).
   *
   * Keeps the most recent `keepRecentSteps` steps verbatim and replaces all
   * older steps with a single summary step (a planning step whose `plan` field
   * holds the compressed text). The summary is generated by calling `model`.
   *
   * This reduces context window consumption without discarding agent state.
   * Only call when history is genuinely long; use `estimateMessagesTokens` to
   * check token count first.
   *
   * @param model           Model used to generate the summary.
   * @param keepRecentSteps Number of recent steps to preserve verbatim (default 5).
   * @returns               Number of steps that were compacted into the summary.
   */
  async compact(
    model: import("../models/types.js").Model,
    keepRecentSteps = 5
  ): Promise<number> {
    if (this.#history.length <= keepRecentSteps) return 0;

    const cutoff = this.#history.length - keepRecentSteps;
    const toSummarize = this.#history.slice(0, cutoff);
    const recent = this.#history.slice(cutoff);

    // Build a minimal message list representing only the steps to summarize.
    const summaryContext: import("../models/types.js").ModelMessage[] = [
      {
        role: "system",
        content:
          "You are a concise summarizer. Compress the following agent history into a short, factual summary that preserves key observations, decisions, and results needed to continue the task. Respond with only the summary text.",
      },
    ];
    for (const step of toSummarize) {
      const msgs = this.#stepToMessages(step);
      summaryContext.push(...msgs);
    }
    summaryContext.push({
      role: "user",
      content: "Summarize the history above into a concise paragraph.",
    });

    let summaryText = "";
    for await (const ev of model.generate(summaryContext, { stream: true, maxTokens: 512 })) {
      if (ev.type === "text_delta" && ev.delta) summaryText += ev.delta;
    }
    summaryText = summaryText.trim() || "(no summary generated)";

    // Replace old steps with a single planning/summary step.
    const summaryStep: import("../types/events.js").PlanningStep = {
      type: "planning",
      plan: summaryText,
      facts: `Compacted ${cutoff} steps.`,
    };

    this.#history = [summaryStep, ...recent];
    this.#msgCache = [
      this.#stepToMessages(summaryStep),
      ...recent.map((s) => this.#stepToMessages(s)),
    ];
    return cutoff;
  }

  /** Returns the number of completed sealed chunks in the current history (B2). */
  get sealedChunkCount(): number {
    const chunkSize = this.#config.chunkSizeSteps ?? 0;
    if (chunkSize === 0) return 0;
    const actionCount = this.#history.filter((s) => this.#isChunkableStep(s)).length;
    return Math.floor(actionCount / chunkSize);
  }

  /** True for step types that count toward B2 chunk boundaries. */
  #isChunkableStep(step: Step): boolean {
    return step.type === "action" || step.type === "tool_use" || step.type === "parallel_tool_use";
  }

  /** Computes the set of history indices that end a sealed chunk (B2). */
  #computeSealedChunkEnds(chunkSize: number): Set<number> {
    const sealedChunkEnds = new Set<number>();
    if (chunkSize === 0) return sealedChunkEnds;
    const actionStepIndices: number[] = [];
    for (let i = 0; i < this.#history.length; i++) {
      if (this.#isChunkableStep(this.#history[i]!)) actionStepIndices.push(i);
    }
    for (let chunk = chunkSize; chunk <= actionStepIndices.length; chunk += chunkSize) {
      const idx = actionStepIndices[chunk - 1];
      if (idx !== undefined) sealedChunkEnds.add(idx);
    }
    return sealedChunkEnds;
  }

  /** Stable representation of system content + tools schema (B1 byte-stability). */
  #buildSystemContent(): string {
    const toolsJson = JSON.stringify(this.#config.toolsSchema, null, 0);
    return `${this.#config.systemPrompt}\n\n<tools>${toolsJson}</tools>`;
  }

  #stepToMessages(step: Step): ModelMessage[] {
    switch (step.type) {
      case "action":
        return [
          {
            role: "assistant",
            content: `<thoughts>${step.thoughts}</thoughts>\n<code>${step.code}</code>`,
          },
          {
            role: "user",
            content: `<observation>${step.observations}</observation>`,
          },
        ];
      case "tool_use":
        // Produce the assistant tool_use block + user tool_result block required
        // by the Anthropic and OpenAI multi-turn tool conversation format.
        return [
          {
            role: "assistant",
            content: [
              ...(step.thoughts
                ? [{ type: "text" as const, text: step.thoughts }]
                : []),
              {
                type: "tool_use" as const,
                id: step.toolCallId,
                name: step.toolName,
                input: step.toolInput,
              },
            ],
          },
          {
            role: "user",
            content: [
              {
                type: "tool_result" as const,
                toolUseId: step.toolCallId,
                content: step.toolOutput || "Tool execution failed with no output.",
                ...(step.isError ? { isError: true as const } : {}),
              },
            ],
          },
        ];
      case "parallel_tool_use":
        // One assistant message with N tool_use blocks + one user message with N
        // tool_result blocks in matching order — required by the Anthropic API
        // when the model calls multiple tools in a single turn.
        return [
          {
            role: "assistant",
            content: [
              ...(step.thoughts
                ? [{ type: "text" as const, text: step.thoughts }]
                : []),
              ...step.calls.map((c) => ({
                type: "tool_use" as const,
                id: c.toolCallId,
                name: c.toolName,
                input: c.toolInput,
              })),
            ],
          },
          {
            role: "user",
            content: step.calls.map((c) => ({
              type: "tool_result" as const,
              toolUseId: c.toolCallId,
              content: c.toolOutput || "Tool execution failed with no output.",
              ...(c.isError ? { isError: true as const } : {}),
            })),
          },
        ];
      case "planning":
        return [
          {
            role: "assistant",
            content: `<plan>${step.plan}</plan>\n<facts>${step.facts}</facts>`,
          },
        ];
      case "final_answer":
        return [];
      case "user_message":
        return [{ role: "user", content: step.content }];
    }
  }
}
