/**
 * End-to-end cross-repo data chain integration tests.
 *
 * Exercises the fixture files in fixtures/data-loop/ to verify schema parity
 * between the TypeScript pipeline (wasmagent-js) and the pre-computed fixture
 * outputs (generated by evomerge).
 *
 *   A. Fixture schema parity — load rollout-branches.v1.jsonl, run it through
 *      the TypeScript toDpoRecord/toPpoRecords, and compare key fields against
 *      the pre-computed dpo-training.v1.jsonl / ppo-training.v1.jsonl fixtures.
 *      Catches drift between the TypeScript exporter and the Python exporter.
 *
 *   B. Schema drift guard — validate the fixture records against rollout-wire.schema.json
 *      and verify that additionalProperties:true / required[] behave correctly.
 *      Catches any schema tightening that would break the Python side, or any
 *      new required field added without updating the fixture.
 */

import { describe, expect, it } from "bun:test";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import type { RankedBranch, RolloutBranchResult, RolloutRecord } from "@wasmagent/core/beta";
import { toDpoRecord, toPpoRecords } from "@wasmagent/core/beta";

// ── Fixture paths ─────────────────────────────────────────────────────────────

const FIXTURE_DIR = join(import.meta.dir, "../../fixtures/data-loop");

function readJsonlLines(filename: string): Record<string, unknown>[] {
  const raw = readFileSync(join(FIXTURE_DIR, filename), "utf8");
  return raw
    .split("\n")
    .filter(Boolean)
    .map((line) => JSON.parse(line) as Record<string, unknown>);
}

function readSchema(filename: string): Record<string, unknown> {
  return JSON.parse(readFileSync(join(FIXTURE_DIR, filename), "utf8")) as Record<string, unknown>;
}

// ── Helpers ───────────────────────────────────────────────────────────────────

/**
 * Convert a rollout-wire JSONL record (as stored in the fixture) into the
 * RolloutBranchResult shape that toDpoRecord / toPpoRecords expect.
 *
 * The fixture uses snake_case; RolloutBranchResult uses camelCase.
 */
function fixtureRecordToBranchResult(rec: Record<string, unknown>): RolloutBranchResult {
  return {
    rolloutId: String(rec.rollout_id ?? ""),
    task: String(rec.task ?? ""),
    branchIndex: Number(rec.branch_index ?? 0),
    temperature: Number(rec.temperature ?? 0.7),
    seed: null,
    sessionId: String(rec.session_id ?? ""),
    trajectory: [],
    toolCallSequence: (rec.tool_call_sequence as Array<Record<string, unknown>>) ?? [],
    finalAnswer: String(rec.final_answer ?? ""),
    buildResult: null,
  };
}

/**
 * Convert fixture record into RolloutRecord for the ranker.
 */
function fixtureRecordToRolloutRecord(rec: Record<string, unknown>): RolloutRecord {
  return {
    rolloutId: String(rec.rollout_id ?? ""),
    branchIndex: Number(rec.branch_index ?? 0),
    finalAnswer: String(rec.final_answer ?? ""),
    objectiveScore: Number(rec.objective_score ?? 0) as 0 | 1,
    task: String(rec.task ?? ""),
  };
}

/**
 * Convert fixture record into RankedBranch (the rank is pre-computed in the fixture).
 */
function fixtureRecordToRankedBranch(rec: Record<string, unknown>): RankedBranch {
  return {
    branchIndex: Number(rec.branch_index ?? 0),
    rank: Number(rec.rank ?? 1),
    objectiveScore: Number(rec.objective_score ?? 0) as 0 | 1,
    judgeScore: 5,
    totalScore: Number(rec.total_score ?? 0),
  };
}

// ── Tests ─────────────────────────────────────────────────────────────────────

describe("three-repo cross-repo data chain", () => {
  it("fixture schema parity: TS toDpoRecord matches pre-computed dpo-training fixture", () => {
    // WHY: The TypeScript toDpoRecord() and the Python TrainingDataExporter.to_dpo()
    // must agree on which branch is chosen/rejected and what the rollout_id is.
    // If either side adds a normalization step (e.g. different task-hash logic,
    // different answer selection) the fixtures diverge silently. This test runs
    // the TypeScript pipeline on the shared fixture and compares key fields
    // against the pre-computed reference output.

    const rolloutLines = readJsonlLines("rollout-branches.v1.jsonl");
    const dpoFixtureLines = readJsonlLines("dpo-training.v1.jsonl");
    const ppoFixtureLines = readJsonlLines("ppo-training.v1.jsonl");

    // Verify manifest expectations
    expect(rolloutLines.length).toBe(2); // 2 branches per the manifest
    expect(dpoFixtureLines.length).toBe(1); // 1 DPO pair
    expect(ppoFixtureLines.length).toBe(2); // 1 PPO record per branch

    const branches = rolloutLines.map(fixtureRecordToBranchResult);
    const rolloutRecords = rolloutLines.map(fixtureRecordToRolloutRecord);
    const ranked = rolloutLines.map(fixtureRecordToRankedBranch).sort((a, b) => a.rank - b.rank);

    // Run the TypeScript pipeline
    const dpo = toDpoRecord(branches, ranked, 0);
    const ppo = toPpoRecords(branches, ranked, 0);

    // ── DPO parity checks ─────────────────────────────────────────────────────
    expect(dpo).not.toBeNull();
    if (dpo !== null) {
      const fixtureDpo = dpoFixtureLines[0]!;
      const fixtureProv = fixtureDpo.provenance as Record<string, unknown>;

      // rollout_id must match
      expect(dpo.provenance.rollout_id).toBe(String(fixtureProv.rollout_id ?? ""));

      // task / prompt must match
      expect(dpo.prompt).toBe(String(fixtureDpo.prompt ?? ""));

      // chosen and rejected answers must match the fixture
      expect(dpo.chosen).toBe(String(fixtureDpo.chosen ?? ""));
      expect(dpo.rejected).toBe(String(fixtureDpo.rejected ?? ""));

      // chosen_branch / rejected_branch indices must agree
      expect(dpo.provenance.chosen_branch).toBe(Number(fixtureProv.chosen_branch ?? -1));
      expect(dpo.provenance.rejected_branch).toBe(Number(fixtureProv.rejected_branch ?? -1));

      // ── Current-schema required fields must be present ─────────────────────
      // n_gram_hash: 16-char hex string
      expect(typeof fixtureProv.n_gram_hash).toBe("string");
      expect(String(fixtureProv.n_gram_hash).length).toBe(16);
      expect(/^[0-9a-f]{16}$/.test(String(fixtureProv.n_gram_hash))).toBe(true);
      // exported_at_ms: non-negative number
      expect(typeof fixtureProv.exported_at_ms).toBe("number");
      expect(Number(fixtureProv.exported_at_ms)).toBeGreaterThanOrEqual(0);

      // ── Removed fields must NOT be present (drift detector) ───────────────
      expect(fixtureProv.task_hash).toBeUndefined();
      expect(fixtureProv.schema_version).toBeUndefined();
      expect(fixtureProv.total_score).toBeUndefined();

      // objective_score.chosen must be 1 (fixture branch 0 passes)
      expect(dpo.provenance.objective_score.chosen).toBe(1);
      expect(dpo.provenance.objective_score.rejected).toBe(0);

      // Fixture schema_version (top-level) must match training-record/v1
      expect(String(fixtureDpo.schema_version ?? "")).toBe("training-record/v1");
    }

    // ── PPO parity checks ─────────────────────────────────────────────────────
    expect(ppo).toHaveLength(2);

    for (const ppoRecord of ppo) {
      const fixtureMatch = ppoFixtureLines.find((line) => {
        const prov = line.provenance as Record<string, unknown>;
        return Number(prov.branch_index) === ppoRecord.provenance.branch_index;
      });
      expect(fixtureMatch).toBeDefined();
      if (fixtureMatch) {
        const fixtureProv = fixtureMatch.provenance as Record<string, unknown>;
        // rollout_id must match
        expect(ppoRecord.provenance.rollout_id).toBe(String(fixtureProv.rollout_id ?? ""));
        // objective_score must match
        expect(ppoRecord.provenance.objective_score).toBe(Number(fixtureProv.objective_score));
        // prompt must match
        expect(ppoRecord.prompt).toBe(String(fixtureMatch.prompt ?? ""));
        // completion must match
        expect(ppoRecord.completion).toBe(String(fixtureMatch.completion ?? ""));
      }
    }

    // ── Provenance source must always be 'wasmagent-rollout' ─────────────────
    if (dpo !== null) {
      expect(dpo.provenance.source).toBe("wasmagent-rollout");
    }
    for (const r of ppo) {
      expect(r.provenance.source).toBe("wasmagent-rollout");
    }
  });

  it("schema drift guard: rollout-wire.schema.json validates fixture records correctly", () => {
    // WHY: The rollout-wire.schema.json is the contract between wasmagent-js and
    // evomerge. If a developer adds a new required field to the TypeScript type
    // without updating the schema — or the schema gets tightened by removing
    // additionalProperties:true — the Python side breaks silently. This test
    // validates that:
    //   1. Each fixture record has all required fields from the schema
    //   2. additionalProperties:true allows unknown fields without error
    //   3. Removing a required field causes a validation failure (guard check)

    // Load the schema from the packages directory (SSOT)
    const schemaPath = join(
      import.meta.dir,
      "../../packages/core/src/ranking/schemas/rollout-wire.schema.json"
    );
    const schema = JSON.parse(readFileSync(schemaPath, "utf8")) as {
      $id?: string;
      $defs?: Record<
        string,
        {
          required?: string[];
          additionalProperties?: boolean;
          properties?: Record<string, unknown>;
        }
      >;
    };

    const rolloutLines = readJsonlLines("rollout-branches.v1.jsonl");

    // ── 1. Extract required fields from the RolloutBranchRecord def ──────────
    const branchDef = schema.$defs?.RolloutBranchRecord;
    expect(branchDef).toBeDefined();

    const requiredFields: string[] = branchDef?.required ?? [];
    expect(requiredFields.length).toBeGreaterThan(0);
    // Spot-check: the canonical required fields must be present in schema
    const expectedRequired = [
      "rollout_id",
      "task",
      "branch_index",
      "temperature",
      "session_id",
      "tool_call_sequence",
      "final_answer",
    ];
    for (const field of expectedRequired) {
      expect(requiredFields).toContain(field);
    }

    // ── 2. Each fixture record must contain ALL required fields ───────────────
    for (const rec of rolloutLines) {
      for (const field of requiredFields) {
        expect(rec).toHaveProperty(field);
      }
    }

    // ── 3. schema_version in fixture must match the $id pattern ───────────────
    // The schema $id is "https://wasmagent.dev/schemas/rollout-wire/v1"
    // The fixture schema_version is "rollout-wire/v1" (the path component after /schemas/)
    const schemaId = String(schema.$id ?? "");
    expect(schemaId).toContain("rollout-wire");
    for (const rec of rolloutLines) {
      const sv = String(rec.schema_version ?? "");
      expect(sv).toContain("rollout-wire");
      // Both should reference the same version tag "v1"
      expect(schemaId).toContain("v1");
      expect(sv).toContain("v1");
    }

    // ── 4. additionalProperties:true — adding unknown field must NOT break ────
    // Simulate a future field being added to the fixture without a schema update.
    const extendedRecord = { ...rolloutLines[0]!, future_field: "some_value" };
    for (const field of requiredFields) {
      expect(extendedRecord).toHaveProperty(field);
    }
    // The additionalProperties flag in the schema def must be true
    expect(branchDef?.additionalProperties).toBe(true);

    // ── 5. Removing a required field MUST fail the manual validation ──────────
    // Simulate what a validator would catch: a record missing "final_answer"
    const missingFinalAnswer = { ...rolloutLines[0] };
    delete missingFinalAnswer.final_answer;

    // Manual validation as a schema consumer would do:
    const missingFields = requiredFields.filter((f) => !(f in missingFinalAnswer));
    expect(missingFields).toContain("final_answer");
    expect(missingFields.length).toBeGreaterThan(0);

    // Similarly, removing "rollout_id" must be detectable:
    const missingRolloutId = { ...rolloutLines[0] };
    delete missingRolloutId.rollout_id;
    const missingIdFields = requiredFields.filter((f) => !(f in missingRolloutId));
    expect(missingIdFields).toContain("rollout_id");

    // ── 6. DpoProvenance schema has additionalProperties:false (strict) ───────
    const dpoProv = schema.$defs?.DpoProvenance;
    expect(dpoProv).toBeDefined();
    expect(dpoProv?.additionalProperties).toBe(false);

    // ── 7. DpoRecord schema has the expected required fields ──────────────────
    const dpoRecordDef = schema.$defs?.DpoRecord;
    expect(dpoRecordDef).toBeDefined();
    const dpoRequired = dpoRecordDef?.required ?? [];
    expect(dpoRequired).toContain("prompt");
    expect(dpoRequired).toContain("chosen");
    expect(dpoRequired).toContain("rejected");
    expect(dpoRequired).toContain("provenance");
  });
});
