/**
 * Multi-agent replay example demonstrating W3C PROV-DM causal edges.
 *
 * Two sub-agents (researcher + writer) produce intermediate results
 * that are consumed by an orchestrator to produce a final answer.
 * The provEdges express causal dependencies so selectByDependency()
 * can extract just the relevant causal subgraph.
 *
 * Run: npx tsx examples/multi-agent-replay/index.ts
 */

import { EventLogReplay, type LoggedEvent, type ProvEdge } from "@wasmagent/devtools";

// Simulate a multi-agent trace with explicit dependency edges
const events: LoggedEvent[] = [
  {
    eventId: "evt-001",
    event: {
      event: "run_start",
      traceId: "trace-multi-agent",
      parentTraceId: null,
      channel: "text",
      timestampMs: 1000,
      data: {},
    } as any,
    provEdges: [],
  },
  {
    eventId: "evt-002",
    event: {
      event: "step_start",
      traceId: "trace-multi-agent",
      parentTraceId: null,
      channel: "text",
      timestampMs: 1001,
      data: { step: 1 },
    } as any,
    provEdges: [
      // Step 1 is associated with the orchestrator agent
      { type: "wasAssociatedWith", from: "evt-002", to: "evt-001" },
    ],
  },
  {
    eventId: "evt-003",
    event: {
      event: "tool_call_end",
      traceId: "trace-multi-agent",
      parentTraceId: null,
      channel: "text",
      timestampMs: 2000,
      data: { toolName: "researcher_agent", result: "Found 3 relevant papers" },
    } as any,
    provEdges: [
      // Researcher output was generated by step 1
      { type: "wasGeneratedBy", from: "evt-003", to: "evt-002" },
    ],
  },
  {
    eventId: "evt-004",
    event: {
      event: "tool_call_end",
      traceId: "trace-multi-agent",
      parentTraceId: null,
      channel: "text",
      timestampMs: 3000,
      data: { toolName: "writer_agent", result: "Draft summary written" },
    } as any,
    provEdges: [
      // Writer output was generated by step 1 and used researcher output
      { type: "wasGeneratedBy", from: "evt-004", to: "evt-002" },
      { type: "wasDerivedFrom", from: "evt-004", to: "evt-003" },
    ],
  },
  {
    eventId: "evt-005",
    event: {
      event: "step_start",
      traceId: "trace-multi-agent",
      parentTraceId: null,
      channel: "text",
      timestampMs: 4000,
      data: { step: 2 },
    } as any,
    provEdges: [],
  },
  {
    eventId: "evt-006",
    event: {
      event: "final_answer",
      traceId: "trace-multi-agent",
      parentTraceId: null,
      channel: "text",
      timestampMs: 5000,
      data: { answer: "Here is the final report combining research and writing." },
    } as any,
    provEdges: [
      // Final answer used both the researcher and writer outputs
      { type: "used", from: "evt-006", to: "evt-003" },
      { type: "used", from: "evt-006", to: "evt-004" },
    ],
  },
];

// Create the replay engine
const replay = new EventLogReplay(events, { traceId: "trace-multi-agent" });

console.log(`Total events: ${replay.eventCount}`);
console.log(`Total steps: ${replay.stepCount}`);
console.log();

// Select by dependency: find all causal ancestors of the final answer
const cursor = replay.selectByDependency("evt-006");
console.log("Causal ancestors of final answer (evt-006):");
for (const ev of cursor.prefixEvents) {
  console.log(`  ${ev.eventId}: ${ev.event.event}`);
}
console.log();
console.log(`Final answer: ${cursor.finalAnswer}`);
console.log();

// Contrast with linear prefix: selecting step 2 includes everything
const linearCursor = replay.select(2);
console.log("Linear prefix (select step 2):");
for (const ev of linearCursor.prefixEvents) {
  console.log(`  ${ev.eventId}: ${ev.event.event}`);
}
console.log();

// The dependency-based selection is more precise: it excludes evt-001 and evt-005
// which are not causally related to the final answer.
console.log("Dependency-based selection excludes unrelated events (evt-001 run_start, evt-005 step_start).");
