/**
 * Compile CapabilityManifest → MCP tool inputSchema fragment.
 *
 * The output is a partial JSON Schema object that can be merged into any
 * tool's inputSchema to surface capability requirements to the MCP host.
 * Also produces a human-readable documentation table.
 */

import type { CapabilityManifest } from "@wasmagent/core";

export interface McpCapabilitySchema {
  /** Partial JSON Schema describing capability constraints. */
  schema: {
    $comment: string;
    properties: Record<string, unknown>;
    required: string[];
  };
  /** Markdown table for tool documentation. */
  documentationTable: string;
  /** Capability tags derived from the manifest (for tool annotations). */
  capabilityTags: string[];
}

/**
 * Compile a CapabilityManifest to MCP-compatible schema fragments.
 *
 * The output `schema` can be spread into a tool's inputSchema `properties`
 * to make capability constraints visible to MCP hosts and human reviewers.
 */
export function compileToMcpSchema(
  manifest: CapabilityManifest,
  toolName = "tool",
): McpCapabilitySchema {
  const properties: Record<string, unknown> = {};
  const required: string[] = [];
  const tags: string[] = [];
  const tableRows: string[] = [];

  // Network access
  if (manifest.allowedHosts.length === 0) {
    tags.push("network:none");
    tableRows.push("| Network | Denied | No outbound connections |");
  } else {
    tags.push("network:restricted");
    tableRows.push(
      `| Network | Allowed | Hosts: ${manifest.allowedHosts.slice(0, 3).join(", ")}${manifest.allowedHosts.length > 3 ? ` +${manifest.allowedHosts.length - 3} more` : ""} |`,
    );
    properties["_allowed_hosts"] = {
      type: "array",
      items: { type: "string", enum: manifest.allowedHosts },
      description: `Outbound network restricted to: ${manifest.allowedHosts.join(", ")}`,
    };
  }

  // Filesystem read
  if (manifest.allowedReadPaths.length === 0) {
    tags.push("fs:no-read");
    tableRows.push("| Filesystem read | Denied | No path access |");
  } else {
    tags.push("fs:restricted-read");
    tableRows.push(
      `| Filesystem read | Allowed | Paths: ${manifest.allowedReadPaths.slice(0, 2).join(", ")}${manifest.allowedReadPaths.length > 2 ? "…" : ""} |`,
    );
  }

  // Filesystem write
  if (manifest.allowedWritePaths.length === 0) {
    tags.push("fs:no-write");
    tableRows.push("| Filesystem write | Denied | No write access |");
  } else {
    tags.push("fs:restricted-write");
    tableRows.push(
      `| Filesystem write | Allowed | Paths: ${manifest.allowedWritePaths.slice(0, 2).join(", ")}${manifest.allowedWritePaths.length > 2 ? "…" : ""} |`,
    );
  }

  // CPU limit
  if (manifest.cpuMs !== undefined) {
    tags.push(`cpu:${manifest.cpuMs}ms`);
    tableRows.push(`| CPU ceiling | ${manifest.cpuMs} ms | Hard timeout per run() call |`);
  }

  // Memory limit
  if (manifest.memoryLimitBytes !== undefined) {
    const mb = (manifest.memoryLimitBytes / (1024 * 1024)).toFixed(0);
    tags.push(`memory:${mb}mb`);
    tableRows.push(`| Memory ceiling | ${mb} MB | Best-effort on WASM kernels |`);
  }

  // Extra capabilities
  for (const cap of manifest.extraCapabilities) {
    tags.push(`extra:${cap}`);
    tableRows.push(`| Extra capability | \`${cap}\` | Explicitly granted |`);
  }

  const table = [
    `## Capability manifest — \`${toolName}\``,
    "",
    "| Capability | Status | Notes |",
    "|---|---|---|",
    ...tableRows,
  ].join("\n");

  return {
    schema: {
      $comment: `Generated by @wasmagent/capability-compiler. Capabilities: ${tags.join(", ")}`,
      properties,
      required,
    },
    documentationTable: table,
    capabilityTags: tags,
  };
}
